### ISSUE TITLE
gestion des photos "ma page dédiée"

### ISSUE THREAD

**Issue by popowych** [cchampou/confidences-app#12]
lorsque j'ai mis deux photos pour une page et que je reviens plus tard sur la page qui me permet de mettre  à jour les infos, les champs sont vides alors qu'il y a bien deux images sur la page dédiée. ça surprend un peu, ne serait-il pas possible de laisser le nom correspondant à l'image chargée ? 
![image](https://user-images.githubusercontent.com/31183142/32421504-9bc0b0a8-c299-11e7-8ab7-d428bbc05322.png)
ici les champs sont vides alors qu'il y a bien 2 images

**Comment by cchampou** [comment]
Solution probablement temporaire que j’espère néanmoins satisfaisante dans un premier temps :
![capture d ecran de 2017-11-06 20-22-53](https://user-images.githubusercontent.com/23266335/32459621-939a9064-c330-11e7-8dcb-1e1a52119041.png)

**Comment by popowych** [comment]
Ok dans ce cas il faut noter en grisé "Aucun nouveau fichier choisi"

**Comment by cchampou** [comment]
![capture d ecran de 2017-11-07 15-14-53](https://user-images.githubusercontent.com/23266335/32497931-7f415244-c3ce-11e7-87e1-b22e51df95a7.png)
Re validation needed
