### ISSUE TITLE
bug ajout image

### ISSUE THREAD

**Issue by popowych** [cchampou/confidences-app#15]
si tu fais un glisser image dans les champs fait pour tu as l'image qui s'affiche, quand tu précédent pour l'enlever tu reviens sur le setup de ta page dédiée et là tu ne vois en rien apparence, pas d'image ajoutée dans ce cadre (alors quand fait elle est bien ajoutée)

**Comment by cchampou** [comment]
Les composants actuels ne permettent de à la fois faire un champs personnalisé ET de supporter le Drag & Drop. Il faut donc choisir, soit on fait comprendre proprement que le drag & drop n'est pas supporté, soit on se tape le vieux champs par défault mais qui supporte le D&D. Sinon, il faudra attendre, car une solution plus complete prendrais beaucoup de temps. Your choice ?
