### ISSUE TITLE
pb de chargement des ruches sur la homepage

### ISSUE THREAD

**Issue by popowych** [cchampou/confidences-app#21]

**Comment by popowych** [comment]
![image](https://user-images.githubusercontent.com/31183142/33243018-f8d94d3c-d2dd-11e7-95d3-7af8f6be1598.png)
assez régulièrement je ne n'arrive pas a visualiser les ruches des parrains sur la homepage, j'ai le petit carré de chargement mais rien ne s'affiche au final

**Comment by cchampou** [comment]
Normal y'en a pas, je t'en met

**Comment by cchampou** [comment]
A priori plus de probleme puisqu'il y a qu moins une entreprise dont la page est publique
