### ISSUE TITLE
Page de l'entreprise XSS

### ISSUE THREAD

**Issue by gadcam** [cchampou/confidences-app#27]
Sur la page de l'entreprise le contenu entrée en URL pour les boutons d'action, il y a une sorte d'XSS : si je mets javascript:alert('Hi') en URL je peux exécuter ce que je veux sur le navigateur de la personne qui clique.

**Comment by cchampou** [comment]
Ces deux liens sont ne peuvent desormais plus contenir autre chose que des url web
