### ISSUE TITLE
gestion de l'ajout des E par l'AA

### ISSUE THREAD

**Issue by popowych** [cchampou/confidences-app#4]
problème lors de saisie du siret, a savoir : 

- si un AA saisi un numéro déjà présent dans la base de donnée des SIREN ça ne devrait pas passer, un message d'alerte doit s'afficher lors de la tentative de validation. Ce message est le suivant : 

> Oups, il semblerait qu’une personne soit déjà en contact avec cette entreprise ou que celle-ci se soit déjà inscrite. Vous pouvez consulter la liste des entreprises déjà marraines [ici](#) et l’ensemble des entreprises déjà contactées [là](#). 

- s'il tente de cliquer sur démarche entreprise et le nb d'entreprise dispo qu'il peut contacter et à zéro un message pop-up d'error doit s'afficher, il dit : 

> Vous avez atteint le nombre maximal d'entreprise qu'il est possible de démarcher en même temps. Il vous faudra patienter jusqu'à tant que l'une d'elle parraine sa première ruche ; vous bénéficierez alors d'un crédit supplémentaire de cinq entreprises à ajouter.

- il faut régler la questions des espaces dans le champ de saisi, 

- si une E s'inscrit il faut que l'AA qui l'a amené soit crédité, donc matchage des SIREN

**Comment by cchampou** [comment]
Les espaces en restent visibles lors de la saisie, mais sont supprimés lors de l'enregistrement. Matchage des SIREN OK. SIREN deja present géré.

**Comment by popowych** [comment]
ok top, reste les raisons sociales à gérer,
