### ISSUE TITLE
setup de la page dédié

### ISSUE THREAD

**Issue by popowych** [cchampou/confidences-app#6]
cf le pdf n°1 que j'ai laissé sur slack, il faut limiter l'affichage des images, et la longueur des textes que l'entreprise peut mettre sur sa page dédiée, pour ça tu as une image que j'ai laissé sur trello qui rappelle les spéc qui doivent etre respectées,

**Comment by popowych** [comment]
au niveau du texte : on a seulement le petit bandeau orange qui s'affiche en haut à droite lorsqu'il y a trop de texte dans la présentation générale 
![image](https://user-images.githubusercontent.com/31183142/32438823-3fa77664-c2ec-11e7-99d0-c92dc7b643c3.png)
en ce qui concerne l'engagement on a rien
Mais le comportement que je voudrais c'est qu'on ne puisse tout simplement pas rentrer plus de 1000 et 3700 caractère, en gros que tu es un décomptes du nb de caractères te restant.

**Comment by popowych** [comment]
![image](https://user-images.githubusercontent.com/31183142/32438874-7e6e73f2-c2ec-11e7-852b-598e067b731d.png)
l'image parle d'elle même, il faut bloquer coute que coute la taille d'image affichée, comme sur fb ou twitter, on affiche un rectangle de 1200x240. pareil pour le logo, c'est du 280x210.

**Comment by popowych** [comment]
j'insiste vraiment sur le respect des dim, il faut qu'on ait qlq chose de propre et d'harmonisé,

**Comment by cchampou** [comment]
Modifications faites, en attente de validation

**Comment by popowych** [comment]
ok ça me va ;) mais par contre la police et sa size ... aie aie aie, j'ai trafiqué en inspectant la page pour obtenir quelque chose de mieux, il faudrait changer ça par la suite
